### ISSUE TITLE
Https?

### ISSUE THREAD

**Issue by sturmenta** [Akashlytics/akashlytics-deploy#101]
I would like to my endpoints have `https` instead of `http`, is there any way to make this possible?

**Comment by sturmenta** [comment]
I understand that this would not be from your side, it would be more from [docker's image](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) or from the suppliers themselves.

**Comment by baktun14** [comment]
> I understand that this would not be from your side, it would be more from [docker's image](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) or from the suppliers themselves.

Hey, yes you're correct.

**Comment by sturmenta** [comment]
I leave here [a way to make tunnel by ssh](https://forum.akash.network/t/torrenting-metasearch-engine-data-science-on-akash/2865) in case it is useful for someone

**Comment by sturmenta** [comment]
with these two methods I was able to add https to my app through cloudflare

[how-to-use-a-custom-domain-with-your-akash-deployment](https://teeyeeyang.medium.com/how-to-use-a-custom-domain-with-your-akash-deployment-5916585734a2)
[tls-termination-of-akash-deployments](https://docs.akash.network/deploy/tls-termination-of-akash-deployments/akash-with-tls-example)
