### ISSUE TITLE
Proposal: Remind Users to Add Funds

### ISSUE THREAD

**Issue by colinlowenberg** [Akashlytics/akashlytics-deploy#26]
We have found that many users deploy using the Akashlytics Deploy tool with the minimum deposit of 5 AKT, and the escrow account runs out of funding. The user is not aware that they need to add funds to keep their deployment running. 

We propose a feature to Alert users when they need to add Funds to their deployment. Some options for implementing this would be:

1. Remind new users when making new deployments.  After creating a lease, encourage users to set a reminder / alert. Give them the option to send a reminder email with a calendar invite or simply generate a calendar invite. 

2. Remind users about existing deployments. When the app is open, alert users if the balance is low / the lease time is less than X days. I propose a 1 day reminder. Perhaps 3 days may be preferred better (due to weekends). On the Deployments views, display the estimated remaining lease time and link them to add funds to the escrow account before their balance runs out. I believe the user must have the Deploy app open to perform this task. This will have the effect of encouraging users to keep Akashlytics Deploy open or open it regularly to check on their deployments.

**Comment by mbeauchamp7** [comment]
Thanks for the feedback, yes those are great ideas. There seems in fact to have something missing in regard to educating and reminding users about the escrow account and balance. Let's chat about our ideas on a call!
