### ISSUE TITLE
Akashlytics can't send the manifest to Akash v0.14.0 providers

### ISSUE THREAD

**Issue by hydrogen18** [Akashlytics/akashlytics-deploy#33]
We've released v0.14.0 of Akash, which is basically just a provider update.

In the process we expanded the definitions we use for our protobuf that defines the manifest structure. At this time we have no forward or reverse compatibility of the providers and the different versions of the client. So you have to use a v0.14.0 client to send manifest to a v0.14.0 provider.

It looks like Akashlytics implemented the send manifest based off the v0.12.0 code, which is no longer accurate.

The handler for the manifest just expects a JSON encoded body, that code is here if you want it for reference:

https://github.com/ovrclk/akash/blob/v0.14.0/provider/gateway/rest/router.go#L386

The manifest is defined in this file:

https://github.com/ovrclk/akash/blob/v0.14.0/manifest/types.go

Primarily we added this new structure

https://github.com/ovrclk/akash/blob/v0.14.0/manifest/types.go#L79

We'd like to work with you to get Akashlytics updated so it can send a manifest the provider can accept. Let me know any additional information you may need so we can get this working again.

**Comment by hydrogen18** [comment]
After looking through the codebase, it seems like there is an incompatibility with something created in this function

https://github.com/Akashlytics/akashlytics-deploy/blob/master/src/shared/utils/deploymentUtils.js#L226

and the v0.14.0 provider.

**Comment by hydrogen18** [comment]
I captured the data we send for the manifest now, and it looks like this for a simple deployment

**Comment by mbeauchamp7** [comment]
@hydrogen18 Hey, thanks for reporting the details, I will look at this during the weekend and fix it asap.

**Comment by mbeauchamp7** [comment]
@hydrogen18 It seems like adding the httpOptions fixes the errors.
