### ISSUE TITLE
Improve RPC node list.  

### ISSUE THREAD

**Issue by mando222** [Akashlytics/akashlytics-deploy#36]
All the RPC nodes have stability and very high ping issues with connecting from the USA.  Would it be possible to have a few US based ones on the default list?

**Comment by baktun14** [comment]
Yes we will eventually deploy some nodes of our own, currently we use the list provided by akash https://raw.githubusercontent.com/ovrclk/net/master/mainnet/api-nodes.txt 

But I think the main issues are the api endpoints being extremely slow (~8 sec to get the list of deployments for an address)

**Comment by baktun14** [comment]
We deployed our own full node. With the ones from the network, we're good to go!
