### ISSUE TITLE
Mac OS developer cant be verified

### ISSUE THREAD

**Issue by MbBrainz** [Akashlytics/akashlytics-deploy#38]
On macOS 12.0.1 Im not able to run the akashlytics-deploy program for both the 0.4.0 and the 0.4.18 dmg versions, Because the developer isnt recognised by Apple. 

<img width="270" alt="Screenshot 2022-01-07 at 14 50 09" src="https://user-images.githubusercontent.com/35366788/148553253-62bda59b-630e-4da6-8345-6c86cde7024d.png">
e

**Comment by baktun14** [comment]
Hi, yes it's in the very near roadmap to fix this issue, have you followed the steps here? https://docs.akash.network/guides/deploy/akashlytics-deploy-installation

**Comment by baktun14** [comment]
Will be fixed in next version! #49
