### ISSUE TITLE
wrong link in Manifest Update

### ISSUE THREAD

**Issue by devenbhooshan** [Akashlytics/akashlytics-deploy#40]
https://github.com/Akashlytics/akashlytics-deploy/blob/79f51bc0ab89baaddea80879203769303b435f09/src/routes/DeploymentDetail/ManifestEditor.js#L78

<img width="1554" alt="Screenshot 2022-01-08 at 1 25 47 PM" src="https://user-images.githubusercontent.com/2411744/148636678-dbb587c7-3ec6-4b1b-9a40-03eae82437c3.png">

**Comment by baktun14** [comment]
Hey thanks for reporting. I will take a look at all the links to the docs to update them.

**Comment by devenbhooshan** [comment]
this is pointing to https://docs.akash.network/guides/cli#part-11.-update-the-deployment
don't think that is correct, correct link is https://docs.akash.network/guides/cli/part-11.-update-the-deployment

**Comment by baktun14** [comment]
Damn you're right, don't know how that `#` got there. Thanks for noticing!
