### ISSUE TITLE
0 AKT is shown as $0.01

### ISSUE THREAD

**Issue by figurestudios** [Akashlytics/akashlytics-deploy#44]
![image](https://user-images.githubusercontent.com/64747030/150855246-7a95bb1e-35f9-4c9e-8e2d-fa8a32b1b36e.png)
**To replicate**
 - switch to testnet
 - import a new wallet with no funds
 - go through the rest of the process of importing your wallet

**Comment by baktun14** [comment]
Thanks for reporting! Will fix it asap.
