### ISSUE TITLE
Very High Latency - Unable to see Deployments

### ISSUE THREAD

**Issue by TheStorm67313** [Akashlytics/akashlytics-deploy#46]
The system is basically unusable this morning. Is there a network problem?

![error](https://user-images.githubusercontent.com/96739294/151198164-d07909b6-f492-40af-bb72-b975edaed87c.PNG)

**Comment by baktun14** [comment]
![image](https://user-images.githubusercontent.com/15185355/151198399-3863937e-7dab-4dd5-b6db-e14bf4fa0125.png)
A lot of nodes from the network are unusable indeed. Try changing it to one that is less latent. We will host our own nodes in the future.
