### ISSUE TITLE
Would be great to have the provider address in overview

### ISSUE THREAD

**Issue by gizmotangle** [Akashlytics/akashlytics-deploy#50]
In Akash Deploy (Version 0.4 I guess),  there was the provider address shown in the overview. Now, there is a new overlay with the provider resources and the provider url, but the akash address is missing. It would be great to find the provider address in this overlay or in the deployment overview.
![provider_overview](https://user-images.githubusercontent.com/20522507/152306973-34ab769d-59ef-4997-aaad-b0bfb510396d.png)

**Comment by baktun14** [comment]
Yes for sure, will add to next release.
