### ISSUE TITLE
Add fund issue

### ISSUE THREAD

**Issue by leonnipp** [Akashlytics/akashlytics-deploy#59]
<img width="333" alt="Screenshot 2022-02-23 at 11 46 52 PM" src="https://user-images.githubusercontent.com/42675642/155354555-ab7fec9c-46d0-4f00-ae40-4753bedc6546.png">
When I add fund then to approve transaction i got this error, even though my wallet have sufficient akt.

**Comment by baktun14** [comment]
Hi, which node are you using? If you're using the smartnode one, it is set to have higher fees than usual. Try changing to the other one. 

This simply means that the fees are insufficient, not your balance.

**Comment by leonnipp** [comment]
It's ok after i set a higher gas fee, thanks for help
