### ISSUE TITLE
Improving wallet generation (UX, minor detail)

### ISSUE THREAD

**Issue by figurestudios** [Akashlytics/akashlytics-deploy#61]
When generating a wallet in the app, you're greeted with 12 or 24 words that you need to write down or paste somewhere. 

After this, you need to press them in order to verify your seed phrase.

Could this be changed so that you can also drag around the words with your mouse? 

If you accidentally skip over a single word, you need to re-do the entire verification after that skipped word at the moment.

**Comment by baktun14** [comment]
Hey, I've never seen a drag and drop implemented for the mnemonic verif but it could be cool I guess. One thing I could implement easily is a reset button so you don't have to click each word one by one if you missed one at the start.

**Comment by baktun14** [comment]
Added a reset button in https://github.com/Akashlytics/akashlytics-deploy/pull/64
