### ISSUE TITLE
Inconsistent frontend (UI, minor)

### ISSUE THREAD

**Issue by figurestudios** [Akashlytics/akashlytics-deploy#63]
Some elements are inconsistent in sizing across Deployments and Dashboard:
![image](https://user-images.githubusercontent.com/64747030/156935627-87037b60-f83d-48c3-bbcb-994f180edfc7.png)

The button is also not in the same place, looks to be about 2 pixels too low on my screen:
![image](https://user-images.githubusercontent.com/64747030/156935520-a5168ff3-9de1-4a65-ad03-744f26301063.png)

The line goes all the way to the end in Deployments, but has gaps in Dashboard:
![image](https://user-images.githubusercontent.com/64747030/156935361-3fdfd8e4-42c1-4283-a83a-f56b87bb02ac.png)
![image](https://user-images.githubusercontent.com/64747030/156935374-a03ea48c-6362-475b-8d79-9495e0a1fa74.png)

**Comment by baktun14** [comment]
You have a good eye! I will fix these in the next versions. Thx

**Comment by baktun14** [comment]
Most of these will be fixed in the next version!
