### ISSUE TITLE
URI and log issue

### ISSUE THREAD

**Issue by medap95** [Akashlytics/akashlytics-deploy#65]
The deployment it's active
URI is stack with 502 Bad Gateaway
Logs are not running (remain black)
Events: miner: undefined [Normal] [Pulled] [Pod] Container image "cryptoandcoffee/akash-pkt-miner:1" already present on machine
miner: undefined [Normal] [Created] [Pod] Created container miner
miner: undefined [Normal] [Started] [Pod] Started container miner
miner: undefined [Normal] [SandboxChanged] [Pod] Pod sandbox changed, it will be killed and re-created.
miner: undefined [Warning] [FailedCreatePodSandBox] [Pod] Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: creating container: write /sys/fs/cgroup/kubepods/pod626eafe1-1268-45eb-ad81-7b5ad1995075/cgroup.procs: device or resource busy: unknown

**Comment by medap95** [comment]
> Hi, what does your sdl look like?

Where do i find it?

**Comment by baktun14** [comment]
It's the file you used to create the deployment. It should be visible in the "View / Edit Manifest" in the deployment detail.

**Comment by medap95** [comment]
> It's the file you used to create the deployment. It should be visible in the "View / Edit Manifest" in the deployment detail.

version: "2.0"
services:
  miner:
    image: chandrastation/pkt_on_akash:v1.0.0
    env:
      - WALLET_ADDR=pkt1q5qxz8w2lza8369hkjw7n59jp4zf8xv87sz8dwk
      - POOL1=http://pool.pktpool.io/diff/8192
      - POOL2=http://pool.pkt.world
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 10
        memory:
          size: 512Mi
        storage:
          size: 256Mi
  placement:
    miner:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        miner:
          denom: uakt
          amount: 1000

deployment:
  miner:
    miner:
      profile: miner
      count: 1

**Comment by medap95** [comment]
Another thing I noted is that also the payment to the escrow it's stopped

**Comment by baktun14** [comment]
I think you should try the `cryptoandcofee` docker image, it's the one in the template gallery.

**Comment by medap95** [comment]
thank yuo
