### ISSUE TITLE
error loading price data

### ISSUE THREAD

**Issue by zouyuxuan** [Akashlytics/akashlytics-deploy#66]
akashlystics deploy version: 0.8.2
operating environment:mac
start app loading settings 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/33485252/158009120-29ef9c8d-c60c-4dfa-acdd-bfb90390ff03.png">

**Comment by baktun14** [comment]
Was the app able to run even with the errors or stopped with the errors?

**Comment by zouyuxuan** [comment]
It can't be run but can stop

**Comment by baktun14** [comment]
Ok will take a look thanks.

**Comment by baktun14** [comment]
I was unable to reproduce the error, but improved the code.
