### ISSUE TITLE
Transaction error when creating a deployment.

### ISSUE THREAD

**Issue by bhickenbottom** [Akashlytics/akashlytics-deploy#67]
While trying to create a new deployment, while submitting the deposit transaction, I receive the following error:

```
Tx has failed...

An error has occured. Log: math/big: cannot unmarshal "NaN" into a *big.Int: tx parse error.
```

I had successfully performed several deployments prior to this, but now that I've received the error, it always occurs.

**Comment by baktun14** [comment]
Hi, can you share your sdl/manifest files please?

**Comment by bhickenbottom** [comment]
I narrowed it down. It happens when specifying cpu units in m, as in "100m".

https://docs.akash.network/intro-to-akash/stack-definition-language

I have completed deployments with this value in the past, however.
