### ISSUE TITLE
Desktop app freezes when Cmd+clicking a link in a manifest file

### ISSUE THREAD

**Issue by jonator** [Akashlytics/akashlytics-deploy#85]
### Problem
I was just playing around trying to learn about how Akash works. When following the "subway" workflow to deploy the simple next.js hello world app, I Cmd+clicked a link in the manifest/yaml to the Akash docs to read more about the stack definitions. However, when I came back to the app, I noticed it was completely frozen and required that I restart the app.

* OS: Mac OS 12.3.1, Desktop app

**Comment by baktun14** [comment]
I'm able to reproduce, I'll try to find a fix.

**Comment by baktun14** [comment]
Found a fix. Will be part of the next release. Thanks for reporting!

**Comment by baktun14** [comment]
The bug has been fixed and released in #86
